[project]
name = "assignment-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imutils>=0.5.4",
    "matplotlib>=3.10.7",
    "opencv-python>=4.12.0.88",
]
